branches:
  only:
  - master
  - "/^v0.*$/"

language: python

python:
- '3.6'

install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
- npm install -g jshint

sudo: required

dist: trusty

group: deprecated-2017Q4

addons:
  postgresql: '9.4'

script:
  - pytest
  - jshint bga_database/static/js/*.js
